HotelManagment/Controllers/CustomerMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelManagment.Controllers
{
    public class CustomerMVCController : Controller
    {
        // GET: Customer
        public ActionResult Customer()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult HotelDetails()
        {
            return View();
        }
        public ActionResult Rooms()
        {
            return View();
        }
    }
}

HotelManagment/Views/CustomerMVC/Customer.cshtml
@model EntityLayer.Model.ViewModel.CustomerViewModel

@{
    ViewBag.Title = "Customer";
}

<h2>Customer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", id = "fullname" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id = "email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control",type="text", id = "contactno"}})
                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", id = "address" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", id = "city" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", id = "password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default" onclick="customers();" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    function customers() {
         var cusObj = {
                    FullName: $("#fullname").val(),
                    Email: $("#email").val(),
                    ContactNo: $("#contactno").val(),
                    Address: $("#address").val(),
                    City: $("#city").val(),
                    Password: $("#password").val(),
        };
        console.log(cusObj);
        $.ajax({
            url: 'https://localhost:44376/api/Customer',
            type: "POST",
            data: cusObj,
            dataType: "json",
            
            success: function (data) {
                alert("success");
            },
            error:  function (jqXHR, textStatus, errorThrown)
            {
                alert(JSON.parse(jqXHR.responseText));
            }
        });

    }
</script>

HotelManagment/Views/CustomerMVC/HotelDetails.cshtml
@model EntityLayer.Model.ViewModel.HoteldetailsViewModel

@{
    ViewBag.Title = "HotelDetails";
}
<link href="~/Content/carListstyle.css" rel="stylesheet" />

<link href="~/Content/packagestyle.css" rel="stylesheet" />

<h2>HotelDetails</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>HoteldetailsViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", id = "city" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", type = "date", id = "date" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default" onclick="customers();" />
            </div>

        </div>
    </div>
    <section class="sec1">
        <div class="everything carList" id="customercarlist" style="margin-bottom: 0">
            <!-- Dynamically Rendered CarList -->
        </div>
    </section>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    function customers() {
        var cusObj = {

            City: $("#city").val(),
            Date: $("#date").val(),
        };
        //var City = $("#city").val();
       
        var hoteldata;

        $.ajax({
            url: 'https://localhost:44376/api/Hoteldetails',
            type: 'POST',
            data: cusObj,
            async: false,
            dataType: 'json',


            success: function (data) {
                debugger
                alert("Successfully!");
                // var Date = $("#date").val();
                hoteldata = JSON.parse(data);
                for (var i = 0; i < hoteldata.length; i++) {
                    $('#customercarlist').append(
                        '<div class="card col-md-3 bgcolor" onClick="toPack(\'' + hoteldata[i].HotelId + '\')">' +
                        '<img src = "../Images/hotel1.jpg" class= "card-img-top imgsize" alt = " Photo" />' +
                        '<div class="card-body center">' +
                        '<h5 class="card-title"> <b>HotelName</b>' + hoteldata[i].HotelName + ' ' + hoteldata[i].City + '</h5>' +
                        '<p class="card-text">' + hoteldata[i].Address + '</p>' +
                        '<p class="card-text">' + hoteldata[i].Pincode + '</p>' +
                        '<p class="card-text">' + hoteldata[i].ContactNo + '</p>' +
                        '<p class="card-text"' + hoteldata[i].Website + '</p>' +
                        '</div>' +
                        '</div >'
                    );
                }

                console.log(typeof (hoteldata));

                console.log(data.City);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(JSON.parse(jqXHR.responseText));
            }
        });
    }

    function toPack(value,date) {
        console.log(value);
         console.log(date);
        //window.location.href = '/CustomerMVC/Rooms?hotelId=' + value;
        window.open("https://localhost:44309/CustomerMVC/Rooms?hotelId=" + value + "&Date=" + date)
    }
</script>

HotelManagment/Views/CustomerMVC/Login.cshtml
@model EntityLayer.Model.ViewModel.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>LoginViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", id = "email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", id = "password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default"  onclick="customers();" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Register here", "Customer")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    function customers() {
        var cusObj = {
            
            Email: $("#email").val(),
            Password: $("#password").val(),
        };
        console.log(cusObj);
        $.ajax({
            url: 'https://localhost:44376/api/Login',
            type: "POST",
            data: cusObj,
            dataType: "json",

            success: function (data) {
                alert("Login Successfully!");
                window.location.href = "/CustomerMVC/HotelDetails"
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(JSON.parse(jqXHR.responseText));
            }
        });

    }
</script>

HotelManagment/Views/CustomerMVC/Rooms.cshtml

@{
    ViewBag.Title = "Rooms";
}

<link href="~/Content/carListstyle.css" rel="stylesheet" />

<link href="~/Content/packagestyle.css" rel="stylesheet" />
<h2>Rooms</h2>


<section class="sec1">
    <div class="everything carList" id="customercarlist" style="margin-bottom: 0">
        <!-- Dynamically Rendered CarList -->
    </div>
</section>
@{
    var hotelId = Request.QueryString["hotelId"];
    var date = Request.QueryString["Date"];
}
<div>
    @Html.ActionLink("Back to Hotel", "HotelDetails")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<!--Imported Scripts-->
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/md5.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var urlParams = new URLSearchParams(window.location.search);
        var hotelId = urlParams.get("hotelId");
        var date = urlParams.get("Date");

        $.ajax({

            url: 'https://localhost:44376/api/RoomDetails',
            type: 'GET',

            data: { HotelId: hotelId, Date: date },
            async: false,
            dataType: 'json',


            success: function (data) {
                roomdata = JSON.parse(data);
                console.log(roomdata);
                for (var i = 0; i < roomdata.length; i++) {
                    var catrgory;
                    if (roomdata[i].RoomCategory == 1) {
                        catrgory = "size >35 m2";
                    }
                    if (roomdata[i].RoomCategory == 2) {
                        catrgory = "size 36-50 m2";
                    }
                    if (roomdata[i].RoomCategory == 3) {
                        catrgory = "size 51-100 m2";
                    }
                    $('#customercarlist').append(
                        '<div class="card col-md-3 bgcolor" onClick="toPack()">' +
                        '<img src = "../Images/hotel1.jpg" class= "card-img-top imgsize" alt = " Photo" />' +
                        '<div class="card-body center">' +
                        '<h5 class="card-title"> <b>RoomNo</b>' + roomdata[i].RoomNo + ' ' + roomdata[i].RoomPrice + '</h5>'+ 
                      
                        '<p class="card-text"> <b>Category</b>' + catrgory + '</p>' +
                        
                        '</div>' +
                        '</div >');
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(JSON.parse(jqXHR.responseText));
            }
        });

    });
</script>

HotelManagment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@

                   <li>@Html.ActionLink("Login", "Login", "CustomerMVC")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>